// import '@kaname-png/plugin-statcord/register'
import '@kaname-png/plugin-subcommands-advanced/register'
import '@sapphire/plugin-editable-commands/register'
import '@sapphire/plugin-i18next/register'
import '@sapphire/plugin-logger/register'
