commit_message: 'chore(i18n): New Crowdin translations for %original_file_name% (%language%)'
append_commit_message: false
files:
  - source: /src/languages/es-ES/**/*.json
    translation: /src/languages/%locale%/**/%original_file_name%
