import { Emojis, LANGUAGES, rootFolder } from '#utils/constants';
import { minutes } from '#utils/function';
import { Language } from '@prisma/client';
import { BucketScope, container, LogLevel } from '@sapphire/framework';
import type { InternationalizationContext } from '@sapphire/plugin-i18next';
import type { LoggerFormatOptions } from '@sapphire/plugin-logger';
import { envParseArray, envParseString, setup } from '@skyra/env-utilities';
import { blue, green, red, yellow } from 'colorette';
import type { ClientOptions } from 'discord.js';
import { Options } from 'discord.js';
import { join } from 'node:path';

setup(join(rootFolder, 'src', '.env'));

export const testServer = ['951101886684082176', '945033113673801799'];
export const OWNERS = envParseArray('CLIENT_OWNERS');

const loggerOptions: LoggerFormatOptions = {
	info: {
		timestamp: {
			pattern: 'HH:mm:ss',
			color: blue
		},
		infix: blue('INFO 〢 ')
	},
	debug: {
		timestamp: {
			pattern: 'HH:mm:ss',
			color: green
		},
		infix: green('DEBUG 〢 ')
	},
	warn: {
		timestamp: {
			pattern: 'HH:mm:ss',
			color: yellow
		},
		infix: yellow('WARN 〢 ')
	},
	error: {
		timestamp: {
			pattern: 'HH:mm:ss',
			color: red
		},
		infix: red('ERROR 〢 ')
	}
};

/* const STAT_CORD_OPTIONS: StatcordOptions = {
	client_id: envParseString('CLIENT_ID'),
	key: envParseString('STATCORD_TOKEN'),
	autopost: false
}; */

export const CLIENT_OPTIONS: ClientOptions = {
	regexPrefix: /^(hey +)?Nino[,! ]/i,
	allowedMentions: { users: [], roles: [] },
	subcommandsAdvanced: { nameCommandsAutogenerated: true },
	caseInsensitiveCommands: true,
	caseInsensitivePrefixes: true,
	defaultPrefix: ['Nino'],
	loadDefaultErrorListeners: false,
	loadMessageCommandListeners: true,
	preventFailedToFetchLogForGuilds: [
		'876339668956893216',
		'877560701416259625',
		'880099532417941524',
		'925909747994071111',
		'844856727517003818',
		'726505646073315408',
		'806611727684599838'
	],
	restTimeOffset: 0,
	shards: 'auto',
	partials: ['MESSAGE', 'CHANNEL', 'USER', 'GUILD_MEMBER'],
	sweepers: {
		...Options.defaultSweeperSettings,
		messages: {
			interval: minutes.toSeconds(3),
			lifetime: minutes.toSeconds(15)
		}
	},
	intents: [
		'GUILDS',
		'GUILD_MEMBERS',
		'GUILD_BANS',
		'GUILD_EMOJIS_AND_STICKERS',
		'GUILD_VOICE_STATES',
		'GUILD_MESSAGES',
		'GUILD_MESSAGE_REACTIONS'
	],
	logger: {
		level: envParseString('NODE_ENV') === 'production' ? LogLevel.Info : LogLevel.Debug,
		format: loggerOptions
	},
	presence: {
		activities: [
			{
				name: 'with logs 📋',
				type: 'PLAYING'
			}
		],
		status: 'online'
	},
	// statcord: STAT_CORD_OPTIONS,
	i18n: {
		fetchLanguage: async (context: InternationalizationContext) => {
			if (!context.guild) return LANGUAGES[Language.EN];

			const data = await container.prisma.guild
				.findUniqueOrThrow({
					where: {
						id: BigInt(context.guild.id)
					}
				})
				.catch(() =>
					container.prisma.guild.create({
						data: {
							id: BigInt(context.guild!.id),
							lang: Language.ES
						}
					})
				);

			return LANGUAGES[data.lang];
		},
		i18next: {
			interpolation: {
				defaultVariables: {
					wrong: Emojis.wrong,
					right: Emojis.right,
					excl: Emojis.excl,
					netual: Emojis.netual,
					setting: Emojis.setting,
					ninoheart: Emojis.ninoheart,
					ninozzz: Emojis.ninozzz
				},
				escapeValue: false
			}
		},
		hmr: {
			enabled: true
		}
	},
	defaultCooldown: {
		delay: 10_000, // 10s
		filteredUsers: OWNERS, // bot owners
		limit: 2, // Limit 2 commands for second
		scope: BucketScope.User // Scope User
	}
};
